/**
 * Cloudflare Workers Environment Types
 *
 * This file provides TypeScript types for Cloudflare Workers bindings
 * configured in wrangler.toml. It's used by `@opennextjs/cloudflare`
 * to type the context returned by `getCloudflareContext()`.
 *
 * @see https://developers.cloudflare.com/workers/runtime-apis/bindings/
 */

interface Hyperdrive {
  /**
   * The connection string to use for database connections.
   * This is dynamically generated by Cloudflare and includes
   * the pooled connection details.
   */
  connectionString: string;
}

/**
 * Cloudflare Workers environment bindings.
 * These are configured in wrangler.toml and made available at runtime.
 */
interface CloudflareEnv {
  /**
   * Hyperdrive binding for edge database connection pooling.
   * Only available in production with Hyperdrive configured.
   */
  HYPERDRIVE?: Hyperdrive;

  /**
   * Static assets binding for serving Next.js assets.
   * Configured automatically by OpenNext.
   */
  ASSETS: Fetcher;

  /**
   * Environment variables passed via wrangler deploy --var
   */
  BETTER_AUTH_SECRET?: string;
  BETTER_AUTH_URL?: string;
  AXIOM_TOKEN?: string;
  AXIOM_DATASET?: string;

  /**
   * DATABASE_URL is used in preview deployments (without Hyperdrive)
   * and during local development.
   */
  DATABASE_URL?: string;

  /**
   * Node environment
   */
  NODE_ENV?: string;
}

/**
 * Augment the global scope for Cloudflare Workers types.
 */
declare global {
  /**
   * The Cloudflare execution context type.
   */
  interface ExecutionContext {
    waitUntil(promise: Promise<unknown>): void;
    passThroughOnException(): void;
  }
}

export type { CloudflareEnv, Hyperdrive };
