# =============================================================================
# InsurFlow Cloudflare Workers Deployment - Reference Documentation
# =============================================================================
#
# This file documents the infrastructure setup for InsurFlow on Cloudflare Workers.
# Actual deployments are managed via GitHub Actions, not Terraform, because:
#
# 1. GitHub Actions handles secrets securely without storing them in tfvars
# 2. Preview deployments need dynamic Worker names (per PR)
# 3. Neon database branching is tightly coupled with the deploy workflow
#
# =============================================================================
# ARCHITECTURE OVERVIEW
# =============================================================================
#
# Production:
#   - Worker: insurflow (deployed on push to main)
#   - URL: https://insurflow.workers.dev
#   - Database: Production Neon branch (main)
#
# Preview (per PR):
#   - Worker: insurflow-preview-pr-{number}
#   - URL: https://insurflow-preview-pr-{number}.workers.dev
#   - Database: Isolated Neon branch (preview/pr-{number})
#
# =============================================================================
# GITHUB SECRETS REQUIRED
# =============================================================================
#
# These secrets must be configured in GitHub repository settings:
# Settings → Secrets and variables → Actions → Secrets
#
# CLOUDFLARE_API_TOKEN    - Cloudflare API token with Workers edit permission
#                           Create at: https://dash.cloudflare.com/profile/api-tokens
#                           Template: "Edit Cloudflare Workers"
#
# CLOUDFLARE_ACCOUNT_ID   - Cloudflare Account ID
#                           Found in: Dashboard → Workers → Overview (right sidebar)
#
# DATABASE_URL            - Production Neon PostgreSQL connection string
#                           Format: postgresql://user:pass@host/db?sslmode=require
#
# BETTER_AUTH_SECRET      - Secret key for session encryption (min 32 chars)
#                           Generate: openssl rand -base64 32
#
# NEON_API_KEY            - Neon API key for database branching
#                           Create at: https://console.neon.tech/app/settings/api-keys
#
# AXIOM_TOKEN (optional)  - Axiom API token for structured logging
# SENTRY_DSN (optional)   - Sentry DSN for error tracking
#
# =============================================================================
# GITHUB VARIABLES REQUIRED
# =============================================================================
#
# These variables can be configured in GitHub repository settings:
# Settings → Secrets and variables → Actions → Variables
#
# NEON_PROJECT_ID         - Neon project ID for database branching
#                           Found in: Console → Project Settings
#
# BETTER_AUTH_URL         - Production auth base URL
#                           Value: https://insurflow.workers.dev
#
# AXIOM_DATASET (optional)          - Axiom dataset name (default: insurflow)
# NEXT_PUBLIC_SENTRY_DSN (optional) - Client-side Sentry DSN
# NEXT_PUBLIC_POSTHOG_KEY (optional) - PostHog project API key
# NEXT_PUBLIC_POSTHOG_HOST (optional) - PostHog host (default: https://app.posthog.com)
#
# =============================================================================
# WRANGLER.TOML CONFIGURATION
# =============================================================================
#
# The wrangler.toml file configures the Cloudflare Worker:
#
# name = "insurflow"                    # Worker name (production)
# main = ".open-next/worker.js"         # Entry point (generated by OpenNext)
# compatibility_date = "2025-01-22"     # Workers runtime version
# compatibility_flags = ["nodejs_compat"] # Enable Node.js APIs
#
# [assets]
# directory = ".open-next/assets"       # Static assets
# binding = "ASSETS"                    # Binding name for assets
#
# =============================================================================
# DEPLOYMENT WORKFLOWS
# =============================================================================
#
# Production (.github/workflows/deploy-production.yml):
#   Trigger: Push to main branch
#   Steps:
#     1. Run database migrations (db:migrate)
#     2. Build with OpenNext (build:cloudflare)
#     3. Deploy via wrangler with secrets
#
# Preview (.github/workflows/deploy-preview.yml):
#   Trigger: Pull request opened/updated
#   Steps:
#     1. Create Neon database branch
#     2. Run migrations on branch
#     3. Build with OpenNext
#     4. Deploy as separate Worker
#     5. Comment on PR with preview URL
#
# Cleanup (.github/workflows/cleanup-preview.yml):
#   Trigger: Pull request closed
#   Steps:
#     1. Delete Cloudflare Worker
#     2. Delete Neon database branch
#
# =============================================================================

# Note: The Terraform resources below are kept for reference but are not used.
# If you need to manage infrastructure via Terraform in the future, you can
# uncomment and adapt these resources.

# resource "cloudflare_workers_script" "insurflow" {
#   account_id = var.cloudflare_account_id
#   name       = var.project_name
#   content    = file("${path.module}/../.open-next/worker.js")
#   module     = true
#
#   compatibility_date  = "2025-01-22"
#   compatibility_flags = ["nodejs_compat"]
#
#   # Environment variables would be set via:
#   # plain_text_binding { ... }
#   # secret_text_binding { ... }
# }
