/**
 * Gemini AI Client
 *
 * Provides a simple interface for generating text using Google's Gemini API.
 * Uses the REST API directly to avoid additional dependencies.
 */

import { env } from "@/env";

/**
 * Gemini model to use.
 * Can be overridden with GEMINI_MODEL in env.
 */
export const GEMINI_MODEL = env.GEMINI_MODEL?.trim() || "gemini-2.5-flash";

/** Base URL for Gemini API */
const GEMINI_API_BASE = "https://generativelanguage.googleapis.com/v1beta";

/**
 * Error thrown when Gemini API is not configured
 */
export class GeminiNotConfiguredError extends Error {
  constructor() {
    super(
      "Gemini API key is not configured. Set GEMINI_API_KEY in your environment.",
    );
    this.name = "GeminiNotConfiguredError";
  }
}

/**
 * Error thrown when Gemini API request fails
 */
export class GeminiApiError extends Error {
  constructor(
    message: string,
    public statusCode?: number,
    public details?: unknown,
  ) {
    super(message);
    this.name = "GeminiApiError";
  }
}

/**
 * Response structure from Gemini API
 */
interface GeminiResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
    finishReason?: string;
  }>;
  error?: {
    message?: string;
    code?: number;
  };
}

interface GeminiStreamChunkResponse {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
  }>;
  error?: {
    message?: string;
    code?: number;
  };
}

function parseSseEventPayloads(event: string): string[] {
  return event
    .split("\n")
    .filter((line) => line.startsWith("data:"))
    .map((line) => line.slice(5).trim())
    .filter(Boolean);
}

/**
 * Options for text generation
 */
export interface GenerateTextOptions {
  /** The prompt to send to the model */
  prompt: string;
  /** Temperature for generation (0-2, default 1) */
  temperature?: number;
  /** Maximum tokens to generate */
  maxOutputTokens?: number;
}

/**
 * Check if Gemini API is configured
 */
export function isGeminiConfigured(): boolean {
  return !!env.GEMINI_API_KEY;
}

/**
 * Generate text using Gemini API
 *
 * @param options - Generation options including prompt
 * @returns Generated text
 * @throws {GeminiNotConfiguredError} If API key is not set
 * @throws {GeminiApiError} If API request fails
 */
export async function generateText(
  options: GenerateTextOptions,
): Promise<string> {
  const { prompt, temperature = 0.7, maxOutputTokens = 4096 } = options;

  if (!env.GEMINI_API_KEY) {
    throw new GeminiNotConfiguredError();
  }

  const url = `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:generateContent`;

  const requestBody = {
    contents: [
      {
        parts: [{ text: prompt }],
      },
    ],
    generationConfig: {
      temperature,
      maxOutputTokens,
    },
  };

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": env.GEMINI_API_KEY,
    },
    body: JSON.stringify(requestBody),
  });

  const data = (await response.json()) as GeminiResponse;

  // Check for API errors
  if (data.error) {
    throw new GeminiApiError(
      data.error.message ?? "Unknown Gemini API error",
      data.error.code,
      data.error,
    );
  }

  if (!response.ok) {
    throw new GeminiApiError(
      `Gemini API request failed with status ${response.status}`,
      response.status,
    );
  }

  // Extract text from response
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new GeminiApiError("No text generated in response", undefined, data);
  }

  return text;
}

/**
 * Stream text using Gemini SSE endpoint.
 *
 * Yields text chunks as they are generated by the model.
 */
export async function* streamText(
  options: GenerateTextOptions,
): AsyncGenerator<string> {
  const { prompt, temperature = 0.7, maxOutputTokens = 4096 } = options;

  if (!env.GEMINI_API_KEY) {
    throw new GeminiNotConfiguredError();
  }

  const url = `${GEMINI_API_BASE}/models/${GEMINI_MODEL}:streamGenerateContent?alt=sse`;

  const requestBody = {
    contents: [
      {
        parts: [{ text: prompt }],
      },
    ],
    generationConfig: {
      temperature,
      maxOutputTokens,
    },
  };

  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": env.GEMINI_API_KEY,
    },
    body: JSON.stringify(requestBody),
  });

  if (!response.ok) {
    let details: unknown;
    let message = `Gemini API request failed with status ${response.status}`;

    try {
      details = (await response.json()) as unknown;
      const errorMessage = (details as { error?: { message?: string } })?.error
        ?.message;
      if (errorMessage) {
        message = errorMessage;
      }
    } catch {
      // Keep generic message when response is not JSON.
    }

    throw new GeminiApiError(message, response.status, details);
  }

  const reader = response.body?.getReader();
  if (!reader) {
    throw new GeminiApiError("Gemini stream body is unavailable");
  }

  const decoder = new TextDecoder();
  let buffer = "";

  const processPayload = (payload: string): string | null => {
    if (payload === "[DONE]") {
      return null;
    }

    let parsed: GeminiStreamChunkResponse;
    try {
      parsed = JSON.parse(payload) as GeminiStreamChunkResponse;
    } catch {
      return "";
    }

    if (parsed.error) {
      throw new GeminiApiError(
        parsed.error.message ?? "Unknown Gemini API error",
        parsed.error.code,
        parsed.error,
      );
    }

    return (
      parsed.candidates?.[0]?.content?.parts
        ?.map((part) => part.text ?? "")
        .join("") ?? ""
    );
  };

  while (true) {
    const { value, done } = await reader.read();
    if (done) break;

    buffer += decoder.decode(value, { stream: true });
    const events = buffer.split("\n\n");
    buffer = events.pop() ?? "";

    for (const event of events) {
      const dataLines = parseSseEventPayloads(event);

      if (dataLines.length === 0) {
        continue;
      }

      for (const payload of dataLines) {
        const textChunk = processPayload(payload);
        if (textChunk === null) {
          return;
        }

        if (textChunk) {
          yield textChunk;
        }
      }
    }
  }

  // Some providers do not end the final SSE frame with an extra blank line.
  // Parse any leftover buffer once to avoid dropping the last response chunk.
  const remainingPayloads = parseSseEventPayloads(buffer);
  for (const payload of remainingPayloads) {
    const textChunk = processPayload(payload);
    if (textChunk === null) {
      return;
    }

    if (textChunk) {
      yield textChunk;
    }
  }
}
